set -g default-terminal "screen-256color"

bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

unbind C-a
set-option -g prefix C-b
bind C-b send-prefix

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on

set -s escape-time 0

# tpm plugins
set -g @plugin 'tmux-plugins/tpm'

# tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark'

#
run '~/.tmux/plugins/tpm/tpm'


set -g @resurrect-dir '~/.tmux/resurrect'
set -g @continuum-restore 'on'
set -g @resurrect-save 'on'
set -g @continuum-logging 'on'

## theme config
set -g pane-border-style fg=green
set -g pane-active-border-style fg=green
